### ISSUE TITLE
processing file 'null'... error with db*CODECOP 4.0.4 command-line

### ISSUE THREAD

**Issue by mhoys** [Trivadis/plsql-cop-cli#8] opened 2021-05-06 13:30 UTC
Hi, 
I installed db*CODECOP 4.0.4 on Windows 10, but I'm always getting the following error when trying to analyse a file:
**processing file 'null'...**

Here's the full output:
Parameters:
- path: C:/dbCODECOPv4/tvdcc-4.0.4/example
- filter: (sql|prc|fnc|pks|pkb|trg|vw|tps|tpb|tbp|plb|pls|rcv|spc|typ|aqt|aqp|ctx|dbl|tab|dim|snp|con|collt|seq|syn|grt|sp|spb|sps|pck)$
- timeout: 10
- complexity: 10
- output: ./tvdcc_report.html
- template: html.xsl
- excel: true
- html: true
- transonly: false
- cleanup: true
- check:
- skip:
- nosonar: true
- license:
- validator: com.trivadis.tvdcc.validators.TrivadisGuidelines3
- genmodel: false

**processing file 'null'...**
Summary:
- Total files: 0
- Total bytes: 0
- Total lines: 0
- Total comment lines: 0
- Total blank lines: 0
- Total net lines: 0
- Total commands: 0
- Total statements (PL/SQL): 0
- Max. cyclomatic complexity: 0
- Max. Halstead volume: 0.0
- Min. maintainability index (MI): 221.0
- Total issues: 0
- Total warnings: 0
- Total errors: 0
- Total processing time in seconds: 0.0

Any idea what could be wrong? I changed the following in tvdcc.cmd:
**set TVDCC_HOME=C:\dbCODECOPv4\tvdcc-4.0.4\\
set JAVA_HOME=C:\Program Files\Java\jdk-12.0.1**
I also tried with jdk1.8.0_211, but the same issue occurs. I really don't see what I'm doing wrong?

Thanks,
Matthias

**Comment by PhilippSalvisberg** [comment] 2021-05-06 14:53
Thanks for reporting this. I can reproduce the issue under Windows 10. Seems to be a platform specific bug. I have to analyze that further.

**Comment by PhilippSalvisberg** [comment] 2021-05-06 19:19
fixed with https://github.com/Trivadis/plsql-cop-cli/releases/tag/v4.0.5

**Closed by PhilippSalvisberg** 2021-05-06 19:19 UTC
Labels: bug
